name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install -y libglew-dev cmake
      - name: Run cmake configure
        run: cmake -B build -S .
      - name: Build
        run: cmake --build build
      - name: Archive shared object
        uses: actions/upload-artifact@v3
        with:
          name: Dynamic library
          path: build/libGL3H.so
